### ISSUE TITLE
feature - JSON output option 

### ISSUE THREAD

**Issue by SongGithub** [hoto/jenkins-credentials-decryptor#4]
when migrating Jenkins, it would be better to let this tool optionally output in JSON format. So that we can automate the following process easier with other tools. 

we have been requested to use Ansible vault to source control the Jenkins Credentials. But doing several dozens of them one by one is too tedious.

**Comment by hoto** [comment]
Very good idea.

Thanks for the PR @rbjorklin 

I must have turned off my GH issues/PR emails as I never noticed any of this 🤔 
I've turned everything on, will see if I'll get them now.

So you periodically dump jenkins credentials and encrypt them with ansible vault?
Interesting 🤔

**Comment by hoto** [comment]
JSON output is now the **default** (can also use the `-o json` flag) in version `1.1.0`.  
The old "text" output can be done with `-o text`

I've also added a `--version` to print out the build version and date.

**Comment by SongGithub** [comment]
> Very good idea.
> 
> Thanks for the PR @rbjorklin
> 
> I must have turned off my GH issues/PR emails as I never noticed any of this 🤔
> I've turned everything on, will see if I'll get them now.
> 
> So you periodically dump jenkins credentials and encrypt them with ansible vault?
> Interesting 🤔

Well it is a one-off task. I had to use a groovy script instead to dump creds in JSON. Good to see now it supports JSON.
